## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [1]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [2]:
a = np.zeros(5)
b = np.zeros((5, 1))
c = np.zeros((10, 2))
d = np.zeros((3, 6, 2))
e = np.zeros((4, 3, 2, 1))

Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [3]:
a = np.ones(5, dtype=int)
b = np.ones((5, 1), dtype=int)
c = np.ones((10, 2), dtype=int)
d = np.ones((3, 6, 2), dtype=int)
e = np.ones((4, 3, 2, 1), dtype=int)

Задание 3.

Выполните для векторов выше `reshape` в
* 2 произвольных компоненты
* 3 произвольных компоненты
* 4 произвольных компоненты

In [4]:
print(f'Old shape: {d.shape}, new shape: {d.reshape(3, -1).shape}')
print(f'Old shape: {e.shape}, new shape: {e.reshape(4, 3, -1).shape}')
print(f'Old shape: {c.shape}, new shape: {c.reshape(5, 2, 2, 1).shape}')

Old shape: (3, 6, 2), new shape: (3, 12)
Old shape: (4, 3, 2, 1), new shape: (4, 3, 2)
Old shape: (10, 2), new shape: (5, 2, 2, 1)


Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [5]:
v = np.random.randint(0, 9, size=(5, 7))

In [6]:
print(v)
print()
print(f'Максимум по 1 оси: {np.max(v, axis=1)}')
print(f'Минимум по 0 оси: {np.min(v, axis=0)}')
print(f'Сумма по всем осям: {np.sum(v)}')
print(f'Среднее по 0 оси: {np.mean(v, axis=0)}')
print(f'Медиана по 1 оси: {np.median(v, axis=1)}')

[[4 4 3 6 0 3 0]
 [1 7 2 3 3 3 6]
 [5 0 5 4 2 7 2]
 [5 3 1 3 2 0 2]
 [2 3 3 4 3 8 1]]

Максимум по 1 оси: [6 7 7 5 8]
Минимум по 0 оси: [1 0 1 3 0 0 0]
Сумма по всем осям: 110
Среднее по 0 оси: [3.4 3.4 2.8 4.  2.  4.2 2.2]
Медиана по 1 оси: [3. 3. 4. 2. 3.]


Задание 6.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [7]:
print(f'shape: {v.shape}')
print(f'0 компонента: {v.shape[0]}')
print(f'1 компонента: {v.shape[1]}')

shape: (5, 7)
0 компонента: 5
1 компонента: 7


Задание 7.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [8]:
print(f'Все числа больше 5: {v[v > 5]}')
sec_arr = v[v < 7]
print(f'Все числа меньше 7 в обратном порядке: {sec_arr[::-1]}')
print(f'Все числа больше 3, кооторые делятся на 4 без остатка: {v[(v > 3) & (v % 4 == 0)]}')
print(f'Все числа, остаток от деления на 5 которых равен 3: {v[v % 5 == 3]}')
print(f'Индекс максимума: {np.argmax(v)}')
print(f'Индекс минимума: {np.argmin(v)}')
print(f'Список с индексами элементов отсортированного массива в исходном (неотсортированном): \n{np.argsort(v)}')

Все числа больше 5: [6 7 6 7 8]
Все числа меньше 7 в обратном порядке: [1 3 4 3 3 2 2 0 2 3 1 3 5 2 2 4 5 0 5 6 3 3 3 2 1 0 3 0 6 3 4 4]
Все числа больше 3, кооторые делятся на 4 без остатка: [4 4 4 4 8]
Все числа, остаток от деления на 5 которых равен 3: [3 3 3 3 3 3 3 3 3 3 8]
Индекс максимума: 33
Индекс минимума: 4
Список с индексами элементов отсортированного массива в исходном (неотсортированном): 
[[4 6 2 5 0 1 3]
 [0 2 3 4 5 6 1]
 [1 4 6 3 0 2 5]
 [5 2 4 6 1 3 0]
 [6 0 1 2 4 3 5]]


Задание 8.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [9]:
vector = np.ones((1, 5), dtype=int)
print(f'Исходный вектор: {vector}')
print(vector * 3)
print(vector / 7)
print(np.power(vector, 2 / 3))
print(np.sin(vector))
print(np.log(vector))

Исходный вектор: [[1 1 1 1 1]]
[[3 3 3 3 3]]
[[0.14285714 0.14285714 0.14285714 0.14285714 0.14285714]]
[[1. 1. 1. 1. 1.]]
[[0.84147098 0.84147098 0.84147098 0.84147098 0.84147098]]
[[0. 0. 0. 0. 0.]]


### Разные инициализации + индексирование (3 балла)

Задание 9.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [10]:
odd_square = np.arange(1, 18, 2)
print(odd_square.reshape((3, 3)))

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


Задание 10.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [11]:
even_square = np.arange(0, 32, 2)
print(even_square[::-1].reshape((4, 4)))

[[30 28 26 24]
 [22 20 18 16]
 [14 12 10  8]
 [ 6  4  2  0]]


Задание 11.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [12]:
field = np.zeros((11, 11), dtype=[('x',float),('y',float)])
field['x'], field['y'] = np.meshgrid(np.arange(-0.5, 0.6, 0.1), np.arange(0.5, -0.6, -0.1))


# Цикл только для красивого вывода. В колабе красивый вывод...
show_field = field.tolist()
for row in show_field:
  print(row)

[(-0.5, 0.5), (-0.4, 0.5), (-0.30000000000000004, 0.5), (-0.20000000000000007, 0.5), (-0.10000000000000009, 0.5), (-1.1102230246251565e-16, 0.5), (0.09999999999999987, 0.5), (0.19999999999999984, 0.5), (0.2999999999999998, 0.5), (0.3999999999999998, 0.5), (0.4999999999999998, 0.5)]
[(-0.5, 0.4), (-0.4, 0.4), (-0.30000000000000004, 0.4), (-0.20000000000000007, 0.4), (-0.10000000000000009, 0.4), (-1.1102230246251565e-16, 0.4), (0.09999999999999987, 0.4), (0.19999999999999984, 0.4), (0.2999999999999998, 0.4), (0.3999999999999998, 0.4), (0.4999999999999998, 0.4)]
[(-0.5, 0.30000000000000004), (-0.4, 0.30000000000000004), (-0.30000000000000004, 0.30000000000000004), (-0.20000000000000007, 0.30000000000000004), (-0.10000000000000009, 0.30000000000000004), (-1.1102230246251565e-16, 0.30000000000000004), (0.09999999999999987, 0.30000000000000004), (0.19999999999999984, 0.30000000000000004), (0.2999999999999998, 0.30000000000000004), (0.3999999999999998, 0.30000000000000004), (0.499999999999999

Задание 12.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [13]:
field = np.eye(8, dtype=int)
field[[0, 2, 4, 6], :] = np.arange(1, 33).reshape(4, 8) % 2
field[[1, 3, 5, 7], :] = np.arange(32).reshape(4, 8) % 2
print(field)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


Задание 13.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [14]:
field = np.eye(8, dtype=int)
field[[0, 2, 4, 6], :] = np.arange(32).reshape(4, 8) % 2
field[[1, 3, 5, 7], :] = np.arange(1, 33).reshape(4, 8) % 2
print(field)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Задание 14.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [15]:
def low_triangle_matrix(size):
  return np.tril(np.ones((size, size), dtype=int))

In [16]:
low_triangle_matrix(5)

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

Задание 15.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [17]:
def high_triangle_matrix(size):
  return np.triu(np.ones((size, size), dtype=int))

In [18]:
high_triangle_matrix(5)

array([[1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1],
       [0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1]])

Задание 16.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [19]:
def reversed_eye(size):
  return np.eye(size, dtype=int)[:, ::-1]

In [20]:
reversed_eye(5)

array([[0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0]])

### Операции + аггрегации (3 балла)

Задание 17.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [21]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [22]:
def expected_value_np(x):
    return np.sum(x) / x.shape[0] 

In [23]:
def dispersion_np(x):
    return np.sum((x - expected_value(x)) ** 2) / x.shape[0]

In [24]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [25]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [26]:
def mean_square_difference_np(y1, y2):
    return np.mean((y1 - y2) ** 2)

In [27]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [28]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [29]:
def mean_abs_difference_np(y1, y2):
    return np.mean(abs(y1 - y2))

In [30]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 20.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [31]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [32]:
def matching_proba_np(y1, y2):
    return (y1 == y2).sum() / len(y1)

In [33]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 21.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

* Необходимо найти границы (индексы), такие, что если мы разделим какой-то из них оба вектора, то в левой части пересекающихся в $y_1$ и $y_2$ нулей будет больше, чем единиц, а в правой - наоборот. Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [34]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)

    return res

In [35]:
# def find_thresholds_np(y1, y2):
#     n = len(y1)

#     res = []
#     match_zeros = np.array((y1 == 0) & (y2 == y1), dtype=int)
#     match_ones = np.array((y1 == y2) & (y2 == 1), dtype=int)
#     if match_ones.sum() / n > 0.5:
#       res.append(0)
#     for i in range(1, n):
#       if (match_zeros[:i] == 1).sum() / i > 0.5 and (match_ones[i:] == 1).sum() / (n - i) > 0.5:
#         res.append(i)
#     if match_zeros.sum() / n > 0.5:
#       res.append(n)

#     return res

In [36]:
def find_thresholds_np(y1, y2):
  match_zeros = np.array((y1 == 0) & (y2 == y1), dtype=int)
  match_ones = np.array((y1 == y2) & (y2 == 1), dtype=int)
  print(match_zeros)
  print(match_ones)

In [37]:
print(find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]))
print()
find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))

[1, 2, 3]

[1 1 0 0]
[0 0 1 1]


In [38]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

[1]
[0]


AssertionError: 
Arrays are not equal

Mismatched elements: 1 / 1 (100%)
 x: array([1])
 y: array(None, dtype=object)

### Разные действия с матрицами (3 балла)

Задание 22.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно пяти** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [39]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))

# (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
# Преобразование 1
data = data @ np.ones((16, 1))
print(data.shape)
# Преобразование 2
data = data.reshape(32, 3, -1)
print(data.shape)
# Преобразование 3
data = data @ np.ones((16, 1))
print(data.shape)
# Преобразование 4
data = data.reshape(32, -1)
print(data.shape)
# Преобразование 5
data = data @ np.ones((3, 1))
print(data.shape)

assert data.shape == (32, 1)

(32, 3, 16, 1)
(32, 3, 16)
(32, 3, 1)
(32, 3)
(32, 1)


Задание 23.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя все данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [40]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

# (∩｀-´)⊃━☆ﾟ.*･｡ﾟ !!!magic!!!
result = (m1 @ W1) @ (W2.reshape(32, 256) @ W2.reshape(256, 32)) @ (m2 @ m2.T)

assert result.shape == (32, 32)

Задание 24.

Последнее испытание для юного мага матриц - приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [ ]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
result = result @ np.ones((32, 3))
result = result / result.max()

assert result.shape == (32, 3)
assert ((result >= 0) & (result <= 1)).all()